In [6]:
import torch
import numpy as np

In [7]:
data=[[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [9]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [10]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [12]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [13]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.0331, 0.6732],
        [0.2833, 0.5492]])

In [14]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.6708, 0.7087, 0.5250],
        [0.8798, 0.8040, 0.0913]])

In [15]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
rand_tensor.shape

torch.Size([2, 3])

In [18]:
rand_tensor.dtype

torch.float32

In [19]:
rand_tensor.device

device(type='cpu')

In [20]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [21]:
 rand_tensor

tensor([[0.6708, 0.7087, 0.5250],
        [0.8798, 0.8040, 0.0913]])

In [22]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.6708, 1.0000, 0.5250],
        [0.8798, 1.0000, 0.0913]])

In [23]:
rand_tensor[0]

tensor([0.6708, 1.0000, 0.5250])

In [24]:
rand_tensor[:,0]

tensor([0.6708, 0.8798])

In [25]:
rand_tensor[:,0]

tensor([0.6708, 0.8798])

In [26]:
rand_tensor[...,-1]

tensor([0.5250, 0.0913])

In [27]:
rand_tensor.sum()

tensor(4.1668)

In [28]:
rand_tensor.sum().item()

4.166823863983154

In [29]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.6708, 1.0000, 0.5250, 0.0000, 0.0000, 0.0000],
        [0.8798, 1.0000, 0.0913, 0.0000, 0.0000, 0.0000]])

In [30]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.6708, 1.0000, 0.5250],
        [0.8798, 1.0000, 0.0913],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [31]:
rand_tensor.mul(ones_tensor)

tensor([[0.6708, 1.0000, 0.5250],
        [0.8798, 1.0000, 0.0913]])

transport

In [32]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.7256, 1.6380],
        [1.6380, 1.7824]])

In [33]:
rand_tensor.add_(5)

tensor([[5.6708, 6.0000, 5.5250],
        [5.8798, 6.0000, 5.0913]])

In [34]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [35]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [36]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [37]:
x = torch.empty(1)
print(x)

tensor([8.4502e-31])


In [38]:
x.size()

torch.Size([1])

In [39]:
x = torch.empty(2,3)
print(x)

tensor([[9.7375e-31, 3.3306e-41, 6.3687e-31],
        [3.3306e-41, 8.9683e-44, 0.0000e+00]])


In [40]:
torch.empty(2,2,3)

tensor([[[-3.6950e-19,  4.4601e-41, -3.6950e-19],
         [ 4.4601e-41,  1.4013e-45,  0.0000e+00]],

        [[ 1.4013e-45,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [41]:
y=x.view(6)
y

tensor([9.7375e-31, 3.3306e-41, 6.3687e-31, 3.3306e-41, 8.9683e-44, 0.0000e+00])

In [42]:
z=x.view(1,-1)
z

tensor([[9.7375e-31, 3.3306e-41, 6.3687e-31, 3.3306e-41, 8.9683e-44, 0.0000e+00]])

In [43]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [44]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [45]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [46]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [47]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [48]:
a[1,1].item()

1.0

In [49]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])